enum TodoStatus {
  "Todo is pending"
  PENDING
  "Todo is completed"
  COMPLETED
}

type Todo {
  "The todo"
  content: String!
  # "The status"
  status: TodoStatus!
}

type Mutation {
  "Creates a new todo and set the status to pending"
  addTodo(content: String): Todo!
}

type Query {
  todos(status: TodoStatus!): [Todo!]!
}
